package com.tech;

public enum PropKeysEnum {
    INPUT_FILE,
    PROP_FILE,
    SRC_FOLDER,
    TARGET_FOLDER,
    QUARANTINE_FOLDER,
    FOLDER_SEQUENCE,
    OPTIONAL_PATH_FIELDS,
    COPY_BLOCK_SIZE,
    USE_STREAM_COPY,
    DATE_FORMAT,
    HELP,
    EXCLUDE_FILE_TYPES,
    EXCLUDE_PATTERNS,
    COPY_THREADS,
    START_INDEX,
    CHECKSUM_SCHEME,
    REPLACE_CHARS,
    GUID_NAME,
    FAIL_FAST,
    SHALLOW_FILE_COMPARISON

}
